### ISSUE TITLE
Program waits infinitely on semaphore "frameRenderingSemaphore" in GPUImageStillCamera while image capture

### ISSUE THREAD

**Issue by aqeelvn** [BradLarson/GPUImage#1114]
Sometime while capturing an image the program waits infinitely in this line:
`dispatch_semaphore_wait(frameRenderingSemaphore, DISPATCH_TIME_FOREVER);` (around line number 223 in file `GPUImageStillCamera.m` .
I am invoking the `- (void)capturePhotoAsImageProcessedUpToFilter:(GPUImageOutput<GPUImageInput> *)finalFilterInChain withCompletionHandler:(void (^)(UIImage *processedImage, NSError *error))block` method to capture image

For time being I have changed the wait time to `DISPATCH_TIME_NOW` and prevent indefinite waiting, but that would result in not capturing any image.

Let me know what details I can provide to help you understand the issue.

Thanks

**Comment by egold** [comment]
@neils4fun -- not sure if your deadlock was caused by the same issues as my deadlock, but in my case, it was because I was dispatching_async to a queue of priority/QoS QOS_CLASS_USER_INTERACTIVE. This effectively meant Thread 1, the UI thread. I was also using a long-press gesture recognizer to do capture (on Thread 1) which caused the deadlock for me. I changed the QoS to QOS_CLASS_USER_INITIATED and it seems to work fine now.
