### ISSUE TITLE
Live video freezes for a second when setting audioEncodingTarget = movieWriter

### ISSUE THREAD

**Issue by raphaklr** [BradLarson/GPUImage#1830]
Hi,

I searched the issues of this repository but didn't find an answer to my question. When I use a `GPUImageVideoCamera` and a `GPUImageMovieWriter` to record live video, the capturing freezes for a second at the beginning of the recording. After some investigation, I noticed that this line caused the freeze: `self.videoCamera.audioEncodingTarget = self.movieWriter;` which is called just before `[self.movieWriter startRecording];`. Unfortunately, I have to create the movieWriter right before starting the record because its initializer takes the size of the output video, which depends on the current orientation of the device.

[This guy](http://stackoverflow.com/questions/14859860/recording-a-video-with-audio-using-gpuimagemoviewriter-without-jerkiness-at-star) asked the same question on stackoverflow last year but didn't get an answer either. Does anybody know a solution to this problem?

**Comment by GidaeYeo** [comment]
Hi,

I faced the same issue and here is my workaround.
For your information, I also have to create the movieWrite right before starting the recording.

This problem happened because setAudioEncodingTarget method internally calls addAudioInputsAndOutputs to set audio in/output to the capture session.

To avoid this issue, I created justSetAudioEncodingTarget method for VideoCamera as below,
(on GPUImageVideoCamera.m)

// just set
-(void)justSetAudioEncodingTarget:(GPUImageMovieWriter*)newValue {
    
    if( newValue == nil ) {
        return;
    }
    addedAudioInputsDueToEncodingTarget = YES;
    
    [super setAudioEncodingTarget:newValue];
}

The following steps is my scenario and I checked out it smoothly worked.

1. Called VideoCamera's addAudioInputsAndOutputs after the VideoCamera was created.
This is not right before starting the recording. :)

2. Set MovieWriter to the VideoCamera by justSetAudioEncodingTarget that I made above.

**Comment by raphaklr** [comment]
@GidaeYeo Thank you!

**Comment by shivamkedia007** [comment]
Hey I am getting this issue. Instead of freezing I get a black screen in this view. 

I've tried the following steps
1. Called VideoCamera's addAudioInputsAndOutputs after the VideoCamera was created.
2.  Set MovieWriter to the VideoCamera this way 

```
videoCamera.audioEncodingTarget = movieWriter
```

But still the black screen exists. Can someone help me with this issue?
