### ISSUE TITLE
Can't re-encode MPEG4 movie

### ISSUE THREAD

**Issue by stephenlv** [BradLarson/GPUImage#185]
Hi, Brad,

I wanna re-encode & filter a MPEG4 video(640X480) to a small one(360X480). It's crashed at the following line:

```
    [assetWriter addInput:assetWriterAudioInput];
```

On simulator, crash log is:

2012-06-07 18:06:02.640 SimpleVideoFileFilter[54232:11f03] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[AVAssetWriter addInput:] AVAssetWriter currently does not support passthrough for the output file type public.mpeg-4 and requires that output settings be specified for each input.'

On the device, it's all crashed when addInput.

Brad, does GPUImage support re-encode MPEG4 movie in the current version? 

Plz help me! Thanks!

**Comment by Fairtoys** [comment]
is this issue solved? Can some one tell me how to solve this? thanks ~~~

**Comment by gonghao** [comment]
I met the same problems.

**Comment by joemwalter** [comment]
When I use the method

 `movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(1280.0, 720.0) fileType:AVFileTypeMPEG4 outputSettings:nil];`
        
I get the following error:

`In order to perform passthrough to file type public.mpeg-4, please provide a format hint in the AVAssetWriterInput initializer`

Seems like GPUImage does not support non-quicktime files. And when I convert my asset to Quicktime it disregards the "Preferred Transform" and videos shot in Landscape come out sideways.

**Comment by luckyOC** [comment]
who can solve this question
