### ISSUE TITLE
Colorspace & optimization

### ISSUE THREAD

**Issue by aelveon** [BradLarson/GPUImage#2059]
Two quick questions (hope this is the right place for them):
1. Is the source image from the movie in linear or sRGB colorspace? It looks like you're creating the texture as if it's linear, but I wanted to make sure it's intentional. Same goes for the renderbuffer.
2. Did you consider using the **EXT_shader_framebuffer_fetch** extension to read directly from the framebuffer instead of sampling from a texture? According to Apple, it should be faster. [source](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html#//apple_ref/doc/uid/TP40008793-CH7-SW23), [supported devices](https://developer.apple.com/library/ios/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/OpenGLESPlatforms/OpenGLESPlatforms.html)
I might start working on a project with GPUImage and I'd like to contribute if I can.

**Comment by BradLarson** [comment]
1) I honestly don't know. I think it's linear, but the only place I'm sure about that is in input direct from the camera (where I'm doing the conversion from YUV to RGB). The movie handling code has always been the weakest in the framework, simply because I don't use it much myself.

2) I've worked with EXT_shader_framebuffer_fetch in other projects, and it's great for custom blend modes and things like that (I think I might have some code using this deep within the Hough transform line detector, in fact). It potentially could be used to run multi-step filters without intermediate textures, having them all operate off of a single input texture / framebuffer. 

However, that would require some significant rearchitecting of the filter pipeline and thinking about the various cases involved. Reading from multiple textures in a pipeline has generally not been the largest performance bottleneck in image processing within the framework, and the memory impact was reduced when I switched to a cached framebuffer architecture. I'm not sure how much you'd gain by completely reworking the framework to employ EXT_shader_framebuffer_fetch everywhere.

**Comment by aelveon** [comment]
Indeed, as long as the intermediary texture doesn't have an impact on performance, there's no need to use the framebuffer fetch extension. We'll see how this goes for long chains of filters though.
As for the colorspace, I guess it should be linear for movies too, but I'll try to figure it out for sure.
You can close the issue now, thank you for your answers!
