### ISSUE TITLE
how to add filter to a certain time range of a video

### ISSUE THREAD

**Issue by leoliuxd** [BradLarson/GPUImage#2077]
i have to add filter to a video,but not the entire video, for example, the first fourth of the video.Will GPUImage do?

**Comment by BradLarson** [comment]
Possibly. You may need to have a filter that has a controlled intensity setting, or uses a mixing blend, so that you could have the filter be on for the first fourth, then turned off via a setting for the remainder. Removing the filter from the chain mid-video might lead to hitching, so you may need to transition its intensity.

**Comment by leoliuxd** [comment]
Thx  @BradLarson ,i will try.

**Comment by ngohuutuan2805** [comment]
@leoliuxd I have the same task, but after two day I did not find the solution yet...
If you could, please give me some advice.
