### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by scottmboring** [BradLarson/GPUImage#214]
I've tried running the example applications with GPUImage and most don't work. The only one that does work is the SimpleImageFilter. Some don't build because of '/usr/local/bin/appledoc: No such file or directory' which I have seen other people having the same issue but it's not clear what to do about it. The other applications build and run; but no image is displayed. The 'FitlerShowcase' in particular would be really nice to see working but as soon as I select something from the list, it shows a blank page. 

I'm having issues with my own application using GPUImage in that it also shows blank images. I've tried running the applications in multiple simulators (Iphone 4.3-5.1 & ipad 4.3-5.1)

This looks like a great library and one that I would really like to take advantage of; thanks for sharing it! Any suggestions for my problem would be greatly appreciated.

**Comment by felixturner** [comment]
"The appledoc thing is due to the framework trying to build the documentation target instead of the project target. Under the Xcode schemes, make sure that if you are trying to build the framework you have either the application or the GPUImage framework selected, and not the Documentation target"

To do this, click where it says "Documentation" at top left, next to the 'Run' button. Xcode will display a drop-down list of build targets.

![screen shot 2015-02-09 at 5 15 07 pm](https://cloud.githubusercontent.com/assets/850329/6119604/e168bde6-b07f-11e4-8d01-04ab633dd7be.png)

**Comment by github2016-yuan** [comment]
@felixturner  is right.I came across the same problem just now and what he says solves it. Thank you!
