### ISSUE TITLE
How to output YUV data from any GPUImageFilter using shaders or GPUImageRawDataOutput ? 

### ISSUE THREAD

**Issue by erickingxu** [BradLarson/GPUImage#2174]
Hi @BradLarson ,
This problem confused me a long time, when I need some YUV data type to do some works from GPUImage library, I used GPUImageRawDataOutput to pull out rgba data and using some third lib to convert  RGBA to yuv, it has a bottleneck in this method.
So do I have do this  on GPU with shader or other method in GPUImage?
Please give some helps ,thx.

**Comment by BradLarson** [comment]
How you approach this will depend entirely on what kind of YUV data you want. There are tons of formats, with multiple configurations. 

This becomes particularly tricky with planar data formats, since OpenGL ES 2.0 does not support multiple output render targets. You'd need to do multi-pass output rendering in that case, once for the Y channel and once for the UV channels. Interleaved YUV data might be able to be rendered in a single pass, but that also has its complexities.

There doesn't exist a standard way of doing this with GPUImage, short of writing your own shaders to convert to a particular YUV format.

**Comment by liwuking** [comment]
Hi @erickingxu  I met the same problem with you, confused me for a week, can you solve it, how to solve, please help me, thank you very much

**Comment by runner365** [comment]
I do in another way: 
I user rgba to write file by avasset, then analyse the file format to get the h264.
