### ISSUE TITLE
GPUImage very slow

### ISSUE THREAD

**Issue by shubham1992agg** [BradLarson/GPUImage#2186]
First of all, I would like to say, I didn't find GPUImage as good library for image processing, even if it's built on OpenGL. 

I found people compared GPUImage with CIFilters, saying it is 40 times faster processing images with 10-20 ms, but no one clearly stated the size of image they have used. I am using an image of size 1080x1920, and applying even simple SepiaFilter takes it 3 - 4 seconds to display the result. On the similar side, when I use CIFilters, it takes 2 seconds to process the result, where I do have room for improvements reducing the time by 4 times. And, if I do the same thing in C or Objective-C natively transforming the bitmaps, i can reduce the time to 30-80 ms. I achieved the same speed in pure Java code for an image of size 1280 x 1280 but I have the limit to single operation for processing.

Second thing, where ever I found tutorials where they conveyed that it is the best library to build a photo editing app, and all the tutorials explained the examples of using camera, and i opened many examples as found in your project, and I found all of them to be focussed on camera. None of them focussed on how to apply effects faster on an image shown to the user presented with the horizontal list of Filters.

According to the tutorials I found, and your comments to existing issues, I found 3 methods to apply the filters to photos, and the trivial being using GPUImageFilter method and getting imageByApplyingFilterToImage: OR using GPUImageView OR may be using GPUPicture. But I am only able to get the trivial solution running which returned nil image for ColorMappingFilters, and unluckily it is the slowest method to apply the filter. And the rest two methods returns me a "nil" image when processed. And, if my way of using them is wrong, then there's no place where I can see how to get them working. 

I don't want to comment on your hard work, but I think it's no more useful to use this library. It does not work properly. And if you can prove me wrong, then I will be very much happy.

Thanks Brad Larson

**Comment by BradLarson** [comment]
At present, providing images to the framework relies on loading these images from a UIImage or NSImage and rendering them into a texture with the help of Core Graphics. There is significant overhead in this process, so the first time an image is uploaded to an OpenGL texture, it takes a while. Once an image is loaded, subsequent processing via `-processImage` is extremely fast. Also, the first time a filter is used at all, the shader program for it needs to be compiled, so you'll see a little overhead from that. The shader is cached after that point.

If I could access the raw bytes behind the images loaded into a UIImage or NSImage and directly memory-map them to a texture at the time of image parsing, I could eliminate much of this overhead. It's for this reason (along with support on Linux and other platforms) that I've started exploring writing my own image loading code that is independent of UIImage or NSImage.

Also, make sure you aren't trying to use a UIImageView for display. That adds another layer of overhead to convert from UIImage to texture back to UIImage, then to a texture again. Go GPUImagePicture -> GPUImageFilter -> GPUImageView to keep the latter half of your processing on the GPU.

Frankly, I built this framework to process live video feeds from the camera, and everything else was added to aid in projects that other people were building using it. My focus is still on camera processing and machine vision, so those are the most performant parts of the framework. The camera allows for direct upload of raw frames via texture caches on iOS, which is why you see 1-2 millisecond processing times for 1080p frames there, even on slower devices. The actual on-GPU processing for most operations is indeed very fast.

I'm sorry if the work I have released and supported for free isn't up to your standards, but you have the entire source code for this framework if you'd like to improve upon the aspects you find to be subpar. Or you can use Core Image or any other means that better achieve your goals.

**Comment by shubham1992agg** [comment]
@BradLarson Your work is great. I really don't want to comment on it, as I can myself not create such a good project. I raised an issue, as I want to use GPU instead of Core Filters of iOS. 
I tried the way, using GPUImagePicture -> GPUImageFilter -> GPUImageView but it doesn't work. The image is empty. Similar to issues raised by others.
The only way I was able to get it working was using UIImageView and UIImage which I found on your blog as to be slow.
