### ISSUE TITLE
Hardest Framework Ever

### ISSUE THREAD

**Issue by richardsongraph** [BradLarson/GPUImage#2252]
I have been developing iOS apps for 9 years and this is still the hardest framework to get to work correctly. I opened a project this morning and tried to build and got this error: /Users/Superman/Library/Developer/Xcode/DerivedData/SOS-gmutnogfunlboygojrlugdgovukn/Build/Intermediates/GPUImage.build/Debug-iphonesimulator/Documentation.build/Script-BC552B3A1558C6FC001F3FFA.sh: line 5: /usr/local/bin/appledoc: No such file or directory

It worked perfect last time. It took me about four days to get the app to work right about a year ago. Now I can't even build a new one from scratch and copy the files because you my copy and paste of old code doesn't seem to work in a new project because a get a whole bunch of other different errors (Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_GPUImageBrightnessFilter", referenced from:
      objc-class-ref in Globals.o). The easiest route for me is to fix the issue above but I cannot seem to find but one other person with the same issue. Any ideas?

**Comment by BradLarson** [comment]
You want to talk hard, try writing this from scratch.

In all seriousness, it sounds like you've somehow got your scheme for the framework set to the documentation target. Xcode randomly sets schemes to that target instead of the framework target for some people. I should just remove the documentation target, because it was submitted by one person and no one ever maintained it. If you set your build scheme for the framework to the framework target, this should build cleanly.

**Comment by richardsongraph** [comment]
Cool, thanks!!! 

I bet it was hard to build. I am looking to build a real photoshop like histogram, that’s really the only thing GPUImage is missing.

Carey
