### ISSUE TITLE
How to move the displaying area of the GPUImageCropFilter?

### ISSUE THREAD

**Issue by xuncai** [BradLarson/GPUImage#2257]
Hi, 
I noticed that the displaying area of the GPUImageCropFilter is also centered to the middle of the view. Is there any way I can move it anywhere I want? Because I am trying to do some animation of the displaying area like moving it from right to left or make it very small and scale it up during the recording and video processing. 
Can anyone give me some hint where I should look into and maybe give me some example codes? Since I am not familiar with the OPENGL codes at all.

And Also if it's possible, maybe we should also add this simple feature to this filter so other user can easily move and scale the displaying area of the crop filter. 
@mattt 
Thanks
Xun @brettg

**Comment by BradLarson** [comment]
The crop filter takes in a rectangle, so all you need to do to move it is to set the origin coordinates within the rectangle. Remember that these coordinates are normalized from 0.0 to 1.0, so you'll need to convert from pixels to that.

**Comment by xuncai** [comment]
Hi Brad thanks for your respond but I think you kind of misunderstand it. So when you are using a crop filter in the example filter showcase, you will see one black bar on top and another one at the bottom, and the displaying area is in between. That is the displaying area I am talking about. And whenever you try to change the size of the cropping area, the height of the cropping area will change and it will always be in the center of the view. And I wanna change the positioning of this displaying area to whereever I want. So that I can create some awesome animation. And I would like to contribute this feature into the crop filter if you think this is a good and useful feature.
And you suggested I change the origin coordiates within the intake rectangle. But it just won't change the position of this displaying area. I tried it for sure it will only change the content inside this displaying area. But the box of displaying the content will always still sitting at the center of the view. 

1. please guide me or give me hint how I can change the positioning of the displaying box which is always centred to the center of the view. 
2. I suggest that we should add this feature to this filter so it will be more useful for other user and if my codes work I am happy to contribute it to this project.

@BradLarson

**Comment by BradLarson** [comment]
That's not so much an issue with the crop filter. The crop filter will crop out a portion of an image, and then that portion will be passed along to the rest of the framework. All the rest of the framework will see is just that image, so whenever that image is finally displayed, it will be centered or oriented however the final display handles it.

If you want the cropped portion to remain in the same location, you're looking for a mask instead of a crop. That way, the entire image remains the same size, with the selected portion the only part of the image that is visible in that area.

Masking like this isn't particularly well supported in this version of the framework, but I will be releasing something soon that will make this easy.
