### ISSUE TITLE
"Unresolved identifier" when including swift libraries

### ISSUE THREAD

**Issue by maxandron** [BradLarson/GPUImage#2260]
Hi,

When adding `use_frameworks!` to my PodFile, suddenly library symbols are not resolved in XCode.
Specifically "GPUImagePixellateFilter".

The library worked fine before adding the `use_frameworks!` line using the bridging header.
I run XCode 7.3

This is my PodFile:
```
platform :ios, '8.0'
use_frameworks!

target 'MyApp'
  ...
  pod 'GPUImage', '~> 0.1.7'
  ...
end
```

Is it something I'm doing wrong or a bug in the project?

Thanks!
Ron.

**Comment by BradLarson** [comment]
Sounds like a bug with CocoaPods or the way it interacts with this framework. If you include the Xcode project directly in your application (the way I use the framework), everything builds fine.

I've never used CocoaPods myself, so I can't be much help there.

**Comment by maxandron** [comment]
Thank you Brad for such a quick reply and pointing me in the next direction.
I'll try importing the library statically.

I wonder why this happened to me only with GPUImage though.. I use plenty of other objective-c based libraries.

**Comment by maxandron** [comment]
In case anyone sees this in the future, the solution is: http://www.innerexception.com/2015/05/cocoapods-useframeworks-means-bridging.html
- So turns out it was my problem

This can be closed. Thank you Brad

**Comment by BradLarson** [comment]
Good to hear. Sorry I can't be more help with Cocoapods issues.

**Comment by JHONYS05** [comment]
🌌

**Comment by support3ds** [comment]
Please allow me to express my experience.

I used to work this lib via cocoapods version 0.39 with success. 
Since upgrading the cocoapods to version 1.0.1, on the same project i'm getting the bellow error:
1. Pods > Pods > GPUImage > GPUFramework.h 
   #import <GPUImage/GLProgram.h>  -> 'GPUImage/GLProgram.h' file not found
2. In a swift file
   import GPUImage -> Could not build Objective-C module 'GPUImage'

The bridging header is clear of related imports.

Am i missing anything? Please advise.

**Update**.
The purpose is to use the gaussian filtering in image.

```
let gpuBlurFilter = GPUImageGaussianBlurFilter()
gpuBlurFilter.blurRadiusInPixels = CGFloat(8.0)
let blurredImage = gpuBlurFilter.imageByFilteringImage(image)
```
