### ISSUE TITLE
Hi Brad - GPUImage issue

### ISSUE THREAD

**Issue by JoeyTrombone** [BradLarson/GPUImage#2567]
Hello Brad,
I'm writing in today to ask for your expert advice on processing videos with filters with 1080p and 4k resolution.

Case: Videoshop (my iOS video editing app) is outputting low quality (grainy) videos after applying filters to 1080p and 4k videos. One example, is a "Black & White" filter; my programmer is currently using simple GPUImageSaturationFilter and changing the Saturation to create the B&W filter. However the end result for high resolution videos are grainy, low quality videos. 

GPUImage is ruining the image in any case: Refer to attached. 
![screenshot 2018-03-29 17 24 57](https://user-images.githubusercontent.com/8396024/38263528-2f20e192-3725-11e8-8aaf-f4b3e6b0bab4.png)
Original is on the right;
On the left there is an image processed by GPUImage.

Let me know if you have any idea on a fix! Would be most appreciated!

**Comment by BradLarson** [comment]
From what I can see, you're not actually recording 1080p output. My guess is that the image is being downsampled at some point in the pipeline. If you're downsampling the video for display to the screen in a preview, make sure you fork off your movie recorder before that point so that you preserve the original resolution of your input frames.

What does the code look like that sets up your processing pipeline and recorder?

**Comment by JoeyTrombone** [comment]
Brad, thank you for your quick response. I'm currently reviewing your input with my dev team. Will hopefully determine something then!
Warmest,
Joe

**Comment by JoeyTrombone** [comment]
You were right Brad. We fixed it! Thank you!
