### ISSUE TITLE
Carthage installation not working "The file “GPUImage.framework” couldn’t be opened because there is no such file."

### ISSUE THREAD

**Issue by shtnkgm** [BradLarson/GPUImage#2573]
I can not install GPUImage using carthage. When you execute the carthage update command, the following error is output to the console.

```
$ carthage update --platform ios
*** Fetching GPUImage
*** Checking out GPUImage at "0.1.7"
*** xcodebuild output can be found in /var/folders/62/nrp34pc96t550_hhml86hmwrr_q2rc/T/carthage-xcodebuild.RYlDnC.log
*** Building scheme "GPUImageFramework" in GPUImage.xcodeproj
Failed to write to /Users/snakagam/Desktop/CameraApp/Carthage/Build/iOS/GPUImage.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “GPUImage.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/snakagam/Desktop/CameraApp/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSFilePath=/Users/snakagam/Desktop/CameraApp/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSUnderlyingError=0x7fb41db08460 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

My development environment is as follows.
```
$ carthage version 
0.29.0
$ xcodebuild -version 
Xcode 9.3
Build version 9E145
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
```

**Comment by shtnkgm** [comment]
The folder called ArchiveIntermediates does not exist under the Carthage / Build folder.

**Comment by shtnkgm** [comment]
My problem is simmilar to Carthage/Carthage#2389

**Comment by psegalen** [comment]
I have the same issue, seems to have something to do with SYMROOT according to https://github.com/Carthage/Carthage/issues/2220

**Comment by IHNEL** [comment]
Hi I have same issue but couldn't resolved by removing SYMROOT as Carthage/Carthage#2220
It always throw below error: 
`Failed to write to /Users/admin/Documents/Projects/ilinus/Carthage/Build/iOS/GPUImage.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “GPUImage.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/admin/Documents/Projects/ilinus/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSFilePath=/Users/admin/Documents/Projects/ilinus/Carthage/Checkouts/GPUImage/build/ArchiveIntermediates/GPUImageFramework/BuildProductsPath/Release-iphoneos/GPUImage.framework, NSUnderlyingError=0x7f96d3e49a20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

I'm using XCode 10.1, Swift 4.2, Carthage 0.31.2
Could anyone please help?

**Comment by IHNEL** [comment]
Finally I resolved this problem.
I used to change the `Derived Data` path in my application's Project Settings and Xcode Preference, which didn't work.

Now I open the file `GPUImage.xcodeproj` under `Carthage/Checkouts/GPUImage/framework/` folder  in my XCode, go to menu `File > Project Settings`, under `Derived Data` section, select `Advanced...`,  change the `Build Location` from `Legacy` to `Xcode Default`.

Go back to Terminal and run `carthage update --platform iOS`, it works like charm!

**Comment by RickeyXiao** [comment]
> Finally I resolved this problem.
> I used to change the `Derived Data` path in my application's Project Settings and Xcode Preference, which didn't work.
> 
> Now I open the file `GPUImage.xcodeproj` under `Carthage/Checkouts/GPUImage/framework/` folder in my XCode, go to menu `File > Project Settings`, under `Derived Data` section, select `Advanced...`, change the `Build Location` from `Legacy` to `Xcode Default`.
> 
> Go back to Terminal and run `carthage update --platform iOS`, it works like charm!

It works, but it's means that i will do this operation every time update carthage ?
