### ISSUE TITLE
Please post public notice to have iOS apps remove GPUImage

### ISSUE THREAD

**Issue by NSProgrammer** [BradLarson/GPUImage#2602]
GPUImage depends on OpenGL, which was deprecated by Apple.  Not building new things on OpenGL is going to be insufficient.  Can you update the README.md of the immensely popular GPUImage project, and potentially communicate to watchers of this project, that GPUImage needs to be removed from their code base?

I hope the cageyness is indicative of the underlying importance to get developers off of OpenGL as a dependency ASAP.

https://twitter.com/NolanOBrien/status/1073652062875934721

**Comment by BradLarson** [comment]
There are plenty of reasons to want to maintain backwards compatibility via OpenGL, particularly for older devices that cannot support Metal. I've previously stated that I'm not actively maintaining this original Objective-C version of the project, in favor of the newer Swift versions [here](https://github.com/BradLarson/GPUImage2) and [here](https://github.com/BradLarson/GPUImage3). The last is the start of a complete rework in Metal, for those who will need it.

My wife and I have not made as much progress with the latter two projects lately, due to the demands of our day jobs. We hope to get the Metal version feature-complete and ready for people to migrate to as a drop-in replacement within the next few months. We'll have a little more time to devote to this after the start of the new year, but we're not paid for any of this work, so it has to be done in our spare time.

Deprecated does not mean removed. Demanding people get off OpenGL ASAP is perhaps an overreaction, given the historical timeframes that Apple has provided for deprecation and removal of other capabilities. It's good to plan for it, but we have at least until early next fall to fully migrate.

**Comment by NSProgrammer** [comment]
All appreciated and understood.  Early next fall is correct, but that is approaching fast and migrating off GPUImage is not an easy task.  GPUImage (1, 2 and 3) are incredibly popular and will have a strong sway on developers that are unaware of the risks.

I just wanted to offer advanced warning since I am not at privilege to disclose why developers will want to remove OpenGL sooner than waiting for official comms beyond the deprecation notice.

I'll be sure to re-up this issue in June when I can disclose more.

**Comment by NSProgrammer** [comment]
I just re-read this line `We hope to get the Metal version feature-complete and ready for people to migrate to as a drop-in replacement within the next few months.`

That will sufficient for sure.  Thanks!  Sorry for the being the squeaky wheel / noisy canary.
